/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "debugbar.openhandler": [],
    "debugbar.clockwork": [
        {
            "name": "id",
            "required": true
        }
    ],
    "debugbar.assets.css": [],
    "debugbar.assets.js": [],
    "debugbar.cache.delete": [
        {
            "name": "key",
            "required": true
        },
        {
            "name": "tags",
            "required": false
        }
    ],
    "debugbar.queries.explain": [],
    "sanctum.csrf-cookie": [],
    "ignition.healthCheck": [],
    "ignition.executeSolution": [],
    "ignition.updateConfig": [],
    "playwright.factory": [],
    "playwright.login": [],
    "playwright.logout": [],
    "playwright.artisan": [],
    "playwright.run-php": [],
    "playwright.csrf-token": [],
    "playwright.routes": [],
    "playwright.current-user": [],
    "dashboard": [],
    "chirps.index": [],
    "chirps.store": [],
    "movies.index": [],
    "movies.show": [
        {
            "name": "movie",
            "required": true,
            "binding": "id"
        }
    ],
    "movie.create": [],
    "movie.store": [],
    "music.index": [],
    "music.store": [],
    "movieFile.getMovieContent": [
        {
            "name": "movieFile",
            "required": true,
            "binding": "id"
        }
    ],
    "thumbnailFile.getThumbnailContent": [
        {
            "name": "thumbnailFile",
            "required": true,
            "binding": "id"
        }
    ],
    "movie.comment.store": [
        {
            "name": "movie",
            "required": true
        }
    ],
    "comment.update": [
        {
            "name": "comment",
            "required": true,
            "binding": "id"
        }
    ],
    "register": [],
    "login": [],
    "password.request": [],
    "password.email": [],
    "password.reset": [
        {
            "name": "token",
            "required": true
        }
    ],
    "password.store": [],
    "verification.notice": [],
    "verification.verify": [
        {
            "name": "id",
            "required": true
        },
        {
            "name": "hash",
            "required": true
        }
    ],
    "verification.send": [],
    "password.confirm": [],
    "password.update": [],
    "logout": []
}
}
export {};
