/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "debugbar.openhandler": [],
    "debugbar.clockwork": [
        {
            "name": "id",
            "required": true
        }
    ],
    "debugbar.assets.css": [],
    "debugbar.assets.js": [],
    "debugbar.cache.delete": [
        {
            "name": "key",
            "required": true
        },
        {
            "name": "tags",
            "required": false
        }
    ],
    "debugbar.queries.explain": [],
    "sanctum.csrf-cookie": [],
    "ignition.healthCheck": [],
    "ignition.executeSolution": [],
    "ignition.updateConfig": [],
    "playwright.factory": [],
    "playwright.login": [],
    "playwright.logout": [],
    "playwright.artisan": [],
    "playwright.run-php": [],
    "playwright.csrf-token": [],
    "playwright.routes": [],
    "playwright.current-user": [],
    "home": [],
    "organization.index": [],
    "organization.store": [],
    "organization.destroy": [
        {
            "name": "organization",
            "required": true,
            "binding": "id"
        }
    ],
    "organization.tree": [
        {
            "name": "organization",
            "required": true,
            "binding": "id"
        }
    ],
    "switchAppModule": [],
    "dashboard": [],
    "reportBug.store": [],
    "organization.saveSettings": [],
    "organization.show": [
        {
            "name": "organization",
            "required": true,
            "binding": "id"
        }
    ],
    "organization.update": [
        {
            "name": "organization",
            "required": true,
            "binding": "id"
        }
    ],
    "organization.update.post": [
        {
            "name": "organization",
            "required": true,
            "binding": "id"
        }
    ],
    "organization.getLogo": [
        {
            "name": "organization",
            "required": true,
            "binding": "id"
        }
    ],
    "absence.index": [],
    "absence.store": [],
    "absence.destroy": [
        {
            "name": "absence",
            "required": true,
            "binding": "id"
        }
    ],
    "absence.denyDestroy": [
        {
            "name": "absence",
            "required": true,
            "binding": "id"
        }
    ],
    "absence.destroyDispute": [
        {
            "name": "absence",
            "required": true,
            "binding": "id"
        }
    ],
    "absence.updateStatus": [
        {
            "name": "absence",
            "required": true,
            "binding": "id"
        }
    ],
    "userAbsenceFilter.store": [],
    "userAbsenceFilter.update": [
        {
            "name": "userAbsenceFilter",
            "required": true,
            "binding": "id"
        }
    ],
    "userAbsenceFilter.destroy": [
        {
            "name": "userAbsenceFilter",
            "required": true,
            "binding": "id"
        }
    ],
    "absence.absencePatch.store": [
        {
            "name": "absence",
            "required": true,
            "binding": "id"
        }
    ],
    "absencePatch.update": [
        {
            "name": "absencePatch",
            "required": true
        }
    ],
    "absencePatch.destroy": [
        {
            "name": "absencePatch",
            "required": true,
            "binding": "id"
        }
    ],
    "absencePatch.updateStatus": [
        {
            "name": "absencePatch",
            "required": true,
            "binding": "id"
        }
    ],
    "dispute.index": [],
    "absenceType.store": [],
    "absenceType.update": [
        {
            "name": "absenceType",
            "required": true,
            "binding": "id"
        }
    ],
    "absenceType.destroy": [
        {
            "name": "absenceType",
            "required": true,
            "binding": "id"
        }
    ],
    "specialWorkingHoursFactor.store": [],
    "specialWorkingHoursFactor.update": [
        {
            "name": "specialWorkingHoursFactor",
            "required": true
        }
    ],
    "specialWorkingHoursFactor.destroy": [
        {
            "name": "specialWorkingHoursFactor",
            "required": true,
            "binding": "id"
        }
    ],
    "group.index": [],
    "group.store": [],
    "group.update": [
        {
            "name": "group",
            "required": true
        }
    ],
    "group.destroy": [
        {
            "name": "group",
            "required": true
        }
    ],
    "homeOfficeDay.store": [],
    "homeOfficeDay.update": [
        {
            "name": "homeOfficeDay",
            "required": true
        }
    ],
    "homeOfficeDay.destroy": [
        {
            "name": "homeOfficeDay",
            "required": true,
            "binding": "id"
        }
    ],
    "homeOfficeDay.denyDestroy": [
        {
            "name": "homeOfficeDay",
            "required": true,
            "binding": "id"
        }
    ],
    "homeOfficeDay.destroyDispute": [
        {
            "name": "homeOfficeDay",
            "required": true,
            "binding": "id"
        }
    ],
    "homeOfficeDay.updateStatus": [
        {
            "name": "homeOfficeDayGenerator",
            "required": true,
            "binding": "id"
        }
    ],
    "homeOfficeDayGenerator.destroy": [
        {
            "name": "homeOfficeDayGenerator",
            "required": true
        }
    ],
    "operatingSite.index": [],
    "operatingSite.store": [],
    "operatingSite.show": [
        {
            "name": "operatingSite",
            "required": true,
            "binding": "id"
        }
    ],
    "operatingSite.update": [
        {
            "name": "operatingSite",
            "required": true,
            "binding": "id"
        }
    ],
    "operatingSite.destroy": [
        {
            "name": "operatingSite",
            "required": true,
            "binding": "id"
        }
    ],
    "operatingSite.operatingTime.store": [
        {
            "name": "operatingSite",
            "required": true,
            "binding": "id"
        }
    ],
    "operatingTime.destroy": [
        {
            "name": "operatingTime",
            "required": true,
            "binding": "id"
        }
    ],
    "notification.index": [],
    "notification.update": [
        {
            "name": "notification",
            "required": true,
            "binding": "id"
        }
    ],
    "notification.readAll": [],
    "profile.update": [],
    "profile.updateSettings": [],
    "user.index": [],
    "user.store": [],
    "user.update": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "user.destroy": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "user.generalInformation": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "user.absences": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "user.documents": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "user.userOrganigram": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "user.profile": [],
    "substitute.update": [],
    "user.timeAccounts": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "user.timeAccountTransactions": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "user.timeStatementDoc": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "workLog.workLogPatch.store": [
        {
            "name": "workLog",
            "required": true,
            "binding": "id"
        }
    ],
    "workLogPatch.update": [
        {
            "name": "workLogPatch",
            "required": true,
            "binding": "id"
        }
    ],
    "workLogPatch.destroy": [
        {
            "name": "workLogPatch",
            "required": true,
            "binding": "id"
        }
    ],
    "workLog.index": [],
    "workLog.store": [],
    "workLog.update": [
        {
            "name": "workLog",
            "required": true,
            "binding": "id"
        }
    ],
    "workLog.destroy": [
        {
            "name": "workLog",
            "required": true,
            "binding": "id"
        }
    ],
    "user.workLog.store": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "user.workLog.index": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "travelLog.store": [],
    "travelLog.update": [
        {
            "name": "travelLog",
            "required": true
        }
    ],
    "user.timeAccount.store": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "timeAccount.update": [
        {
            "name": "timeAccount",
            "required": true,
            "binding": "id"
        }
    ],
    "timeAccount.destroy": [
        {
            "name": "timeAccount",
            "required": true,
            "binding": "id"
        }
    ],
    "timeAccountTransaction.store": [],
    "timeAccountSetting.store": [],
    "customer.index": [],
    "customer.store": [],
    "customer.show": [
        {
            "name": "customer",
            "required": true,
            "binding": "id"
        }
    ],
    "customer.update": [
        {
            "name": "customer",
            "required": true,
            "binding": "id"
        }
    ],
    "customer.destroy": [
        {
            "name": "customer",
            "required": true
        }
    ],
    "customer.customerNoteFolder.store": [
        {
            "name": "customer",
            "required": true,
            "binding": "id"
        }
    ],
    "customerNoteFolder.update": [
        {
            "name": "customerNoteFolder",
            "required": true,
            "binding": "id"
        }
    ],
    "customerNoteFolder.destroy": [
        {
            "name": "customerNoteFolder",
            "required": true,
            "binding": "id"
        }
    ],
    "customer.customerNoteEntry.store": [
        {
            "name": "customer",
            "required": true,
            "binding": "id"
        }
    ],
    "customerNoteEntry.update": [
        {
            "name": "customerNoteEntry",
            "required": true,
            "binding": "id"
        }
    ],
    "customerNoteEntry.destroy": [
        {
            "name": "customerNoteEntry",
            "required": true,
            "binding": "id"
        }
    ],
    "customerNoteEntry.getFile": [
        {
            "name": "customerNoteEntry",
            "required": true,
            "binding": "id"
        }
    ],
    "customer.customerContact.store": [
        {
            "name": "customer",
            "required": true,
            "binding": "id"
        }
    ],
    "customerContact.update": [
        {
            "name": "customerContact",
            "required": true,
            "binding": "id"
        }
    ],
    "customerContact.destroy": [
        {
            "name": "customerContact",
            "required": true,
            "binding": "id"
        }
    ],
    "customer.customerOperatingSite.store": [
        {
            "name": "customer",
            "required": true,
            "binding": "id"
        }
    ],
    "customerOperatingSite.update": [
        {
            "name": "customerOperatingSite",
            "required": true,
            "binding": "id"
        }
    ],
    "customerOperatingSite.destroy": [
        {
            "name": "customerOperatingSite",
            "required": true,
            "binding": "id"
        }
    ],
    "ticket.index": [],
    "ticket.store": [],
    "ticket.update": [
        {
            "name": "ticket",
            "required": true,
            "binding": "id"
        }
    ],
    "ticket.destroy": [
        {
            "name": "ticket",
            "required": true,
            "binding": "id"
        }
    ],
    "ticket.accept": [
        {
            "name": "ticket",
            "required": true,
            "binding": "id"
        }
    ],
    "ticket.finish": [
        {
            "name": "ticket",
            "required": true,
            "binding": "id"
        }
    ],
    "ticket.unfinish": [
        {
            "name": "ticket",
            "required": true,
            "binding": "id"
        }
    ],
    "ticket.ticketRecord.store": [
        {
            "name": "ticket",
            "required": true,
            "binding": "id"
        }
    ],
    "ticketRecord.update": [
        {
            "name": "ticketRecord",
            "required": true,
            "binding": "id"
        }
    ],
    "ticketRecord.destroy": [
        {
            "name": "ticketRecord",
            "required": true
        }
    ],
    "ticketRecordFile.show": [
        {
            "name": "ticketRecordFile",
            "required": true,
            "binding": "id"
        }
    ],
    "ticketRecordFile.destroy": [
        {
            "name": "ticketRecordFile",
            "required": true,
            "binding": "id"
        }
    ],
    "ticketRecordFile.getContent": [
        {
            "name": "ticketRecordFile",
            "required": true,
            "binding": "id"
        }
    ],
    "ticketFile.show": [
        {
            "name": "ticketFile",
            "required": true,
            "binding": "id"
        }
    ],
    "ticketFile.destroy": [
        {
            "name": "ticketFile",
            "required": true,
            "binding": "id"
        }
    ],
    "ticketFile.getContent": [
        {
            "name": "ticketFile",
            "required": true,
            "binding": "id"
        }
    ],
    "login": [],
    "password.request": [],
    "password.email": [],
    "password.reset": [
        {
            "name": "token",
            "required": true
        }
    ],
    "password.store": [],
    "verification.notice": [],
    "verification.verify": [
        {
            "name": "id",
            "required": true
        },
        {
            "name": "hash",
            "required": true
        }
    ],
    "verification.send": [],
    "password.confirm": [],
    "password.update": [],
    "logout": []
}
}
export {};
