/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "debugbar.openhandler": [],
    "debugbar.clockwork": [
        {
            "name": "id",
            "required": true
        }
    ],
    "debugbar.assets.css": [],
    "debugbar.assets.js": [],
    "debugbar.cache.delete": [
        {
            "name": "key",
            "required": true
        },
        {
            "name": "tags",
            "required": false
        }
    ],
    "debugbar.queries.explain": [],
    "sanctum.csrf-cookie": [],
    "ignition.healthCheck": [],
    "ignition.executeSolution": [],
    "ignition.updateConfig": [],
    "playwright.factory": [],
    "playwright.login": [],
    "playwright.logout": [],
    "playwright.artisan": [],
    "playwright.run-php": [],
    "playwright.csrf-token": [],
    "playwright.routes": [],
    "playwright.current-user": [],
    "home": [],
    "organization.index": [],
    "organization.store": [],
    "organization.destroy": [
        {
            "name": "organization",
            "required": true,
            "binding": "id"
        }
    ],
    "organization.tree": [
        {
            "name": "organization",
            "required": true,
            "binding": "id"
        }
    ],
    "dashboard": [],
    "user.index": [],
    "user.store": [],
    "user.update": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "user.destroy": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "user.generalInformation": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "user.absences": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "user.timeAccounts": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "user.timeAccountTransactions": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "user.userOrganigram": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "user.profile": [],
    "organization.saveSettings": [],
    "organization.show": [
        {
            "name": "organization",
            "required": true,
            "binding": "id"
        }
    ],
    "organization.update": [
        {
            "name": "organization",
            "required": true,
            "binding": "id"
        }
    ],
    "absence.index": [],
    "absence.store": [],
    "absence.update": [
        {
            "name": "absence",
            "required": true,
            "binding": "id"
        }
    ],
    "absence.updateStatus": [
        {
            "name": "absence",
            "required": true,
            "binding": "id"
        }
    ],
    "absenceType.store": [],
    "absenceType.update": [
        {
            "name": "absenceType",
            "required": true,
            "binding": "id"
        }
    ],
    "absenceType.destroy": [
        {
            "name": "absenceType",
            "required": true,
            "binding": "id"
        }
    ],
    "specialWorkingHoursFactor.store": [],
    "specialWorkingHoursFactor.update": [
        {
            "name": "specialWorkingHoursFactor",
            "required": true
        }
    ],
    "specialWorkingHoursFactor.destroy": [
        {
            "name": "specialWorkingHoursFactor",
            "required": true,
            "binding": "id"
        }
    ],
    "group.index": [],
    "group.store": [],
    "group.update": [
        {
            "name": "group",
            "required": true
        }
    ],
    "group.destroy": [
        {
            "name": "group",
            "required": true
        }
    ],
    "workLogPatch.store": [],
    "workLogPatch.update": [
        {
            "name": "workLogPatch",
            "required": true,
            "binding": "id"
        }
    ],
    "workLogPatch.destroy": [
        {
            "name": "workLogPatch",
            "required": true,
            "binding": "id"
        }
    ],
    "workLog.index": [],
    "workLog.store": [],
    "user.workLog.index": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "travelLog.store": [],
    "travelLog.update": [
        {
            "name": "travelLog",
            "required": true
        }
    ],
    "operatingSite.index": [],
    "operatingSite.store": [],
    "operatingSite.show": [
        {
            "name": "operatingSite",
            "required": true,
            "binding": "id"
        }
    ],
    "operatingSite.update": [
        {
            "name": "operatingSite",
            "required": true,
            "binding": "id"
        }
    ],
    "operatingSite.destroy": [
        {
            "name": "operatingSite",
            "required": true,
            "binding": "id"
        }
    ],
    "operatingTime.store": [],
    "operatingTime.destroy": [
        {
            "name": "operatingTime",
            "required": true,
            "binding": "id"
        }
    ],
    "user.timeAccount.store": [
        {
            "name": "user",
            "required": true,
            "binding": "id"
        }
    ],
    "timeAccount.update": [
        {
            "name": "timeAccount",
            "required": true,
            "binding": "id"
        }
    ],
    "timeAccount.destroy": [
        {
            "name": "timeAccount",
            "required": true,
            "binding": "id"
        }
    ],
    "timeAccountTransaction.store": [],
    "timeAccountSetting.store": [],
    "dispute.index": [],
    "notification.update": [
        {
            "name": "notification",
            "required": true,
            "binding": "id"
        }
    ],
    "profile.update": [],
    "register": [],
    "login": [],
    "password.request": [],
    "password.email": [],
    "password.reset": [
        {
            "name": "token",
            "required": true
        }
    ],
    "password.store": [],
    "verification.notice": [],
    "verification.verify": [
        {
            "name": "id",
            "required": true
        },
        {
            "name": "hash",
            "required": true
        }
    ],
    "verification.send": [],
    "password.confirm": [],
    "password.update": [],
    "logout": []
}
}
export {};
